name: Deploy to Render

on:
  push:
    branches:
      - main  # You can change this to another branch if needed

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add deployment status
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{
                "state": "success",
                "target_url": "https://hubster.onrender.com",
                "description": "Deployed to Render",
                "context": "Render Deployment"
              }' \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}
